stages:
  - nightly
  - stable
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq

nightly:
  image: 'rustlang/rust:nightly'
  stage: nightly
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

stable:
  image: 'rust:latest'
  stage: stable
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

cache:
  paths:
    - apt/
    - cargo/
    - target/