dist: trusty
language: rust
sudo: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

rust:
  - stable
  - beta
  - nightly

os:
  - linux

install:
  - rustc -Vv
  - cargo -Vv

  # Install kcov.
  - ls -al
  - mkdir -p ~/.cargo/bin
  - sh scripts/install_kcov.sh
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
  - export RUSTFLAGS="-C link-dead-code"
  - kcov --version

script: "./scripts/run-tests.sh"