dist: bionic
language: rust
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly

os:
  - linux

before_script: cargo install cargo-tarpaulin

script: "./scripts/run-tests.sh"

after_success: cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID