dist: bionic
language: rust
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly

os:
  - linux

before_script:
  - cargo install cargo-tarpaulin

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - ./scripts/run-tests.sh
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D warnings

after_success:
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID