dist: trusty
language: rust
sudo: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

rust:
  - stable
  - beta
  - nightly

os:
  - linux

before_script:
  - cargo install cargo-tarpaulin

script: "./scripts/run-tests.sh"

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi