dist: bionic
language: rust
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly

os:
  - linux

before_script: cargo install cargo-tarpaulin

before_script:
  - if [ "$TRAVIS_RUST_VERSION" = 'stable' ]; then rustup component add rustfmt; fi
  - if [ "$TRAVIS_RUST_VERSION" = 'stable' ]; then rustup component add clippy; fi

script:
  - ./scripts/run-tests.sh
  - if [ "$TRAVIS_RUST_VERSION" = 'stable' ]; then cargo fmt --all -- --check; fi
  - if [ "$TRAVIS_RUST_VERSION" = 'stable' ]; then cargo clippy --all -- -D warnings; fi

after_success: cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID