[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["development-tools", "development-tools::build-utils"]
description = "Generate 'cargo:rustc-env' instructions via 'build.rs' for use in your code via the env! macro"
documentation = "http://docs.rs/vergen"
edition = "2018"
homepage = "http://github.com/rustyhorde/vergen"
keywords = ["cargo", "instructions", "build", "tool"]
license = "MIT OR Apache-2.0"
name = "vergen"
readme = "README.md"
repository = "https://github.com/rustyhorde/vergen"
version = "6.0.0"

[features]
default = ["build", "cargo", "git", "rustc", "si"]
build = ["time"]
cargo = []
git = ["git2", "time"]
rustc = ["rustc_version"]
si = ["sysinfo"]

[dependencies]
anyhow = "1"
cfg-if = "1"
time = { version = "0.3", optional = true, features = ["local-offset", "formatting", "macros"] }
enum-iterator = "0"
getset = "0"
git2 = { version = "0", optional = true, default-features = false }
rustc_version = { version = "0.4.0", optional = true }
sysinfo = { version = "=0.19", optional = true, default-features = false }
thiserror = "1"

[build-dependencies]
time = { version = "0.3", features = ["formatting"] }
rustversion = "1"

[dev-dependencies]
lazy_static = "1"
regex = "1"
serial_test = "0"

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
